# Generated by Django 3.1.1 on 2021-01-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HD_app', '0002_auto_20210125_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
