# Generated by Django 3.1.1 on 2021-01-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HD_app', '0003_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='care',
        ),
        migrations.RemoveField(
            model_name='company',
            name='care_substitute',
        ),
        migrations.DeleteModel(
            name='Customer2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
