# Generated by Django 3.1.1 on 2021-01-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HD_app', '0004_auto_20210125_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD_app.document', verbose_name='Dokument'),
        ),
    ]
