# Generated by Django 3.1.1 on 2021-01-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HD_app', '0005_auto_20210125_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address2',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
    ]
