FROM alseambusher/crontab-ui
LABEL maintainer = "Gobit"

RUN apk add bash
# COPY ./wait-for-it/wait-for-it.sh /crontab-ui/wait-for-it.sh
# COPY ./dockerfiles/cron/supervisord.conf /etc/supervisord.conf


